# Generated by Django 2.1.2 on 2019-02-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190210_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mentor',
            field=models.CharField(default='gary', max_length=100),
            preserve_default=False,
        ),
    ]
