# Generated by Django 2.1.2 on 2019-02-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailcontact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcontact',
            old_name='message',
            new_name='content',
        ),
    ]
